TheThreeDevs/amazon-clone

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/ProductsHome.js, amazon-clone/client/src/Components/ProductsList.css, amazon-clone/client/src/Components/ProductsList.js, amazon-clone/client/src/Components/SingleProduct.css, amazon-clone/client/src/Components/SingleProduct.js, amazon-clone/package-lock.json, amazon-clone/package.json
@emmanuel-a-g Can you check the code when you have time. This is just adding a page where you can see the products of the different categories.
=> Products list

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/BottomCarousel.js, amazon-clone/client/src/Components/Carousel.js, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/PrivateRoute.js, amazon-clone/client/src/Components/SignUp.js, amazon-clone/client/src/contexts/AuthContext.js
@leal10 can you please review? Thanks!
=> Firestore adds user into cloud database

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Basket.css, amazon-clone/client/src/Components/Basket.js, amazon-clone/client/src/Components/ProductsList.js
@emmanuel-a-g Here is the logic you need, can you check the code out and merge whenever you have a chance. Thanks
=> Basket sub total

amazon-clone/client/src/Components/SingleProduct.js
@emmanuel-a-g Added the feature that takes the user to the cart when they click on the Buy Now button and also adds the item to the cart. Can you merge this when you get a chance. Thanks
=> Added the buy now feature

amazon-clone/client/src/Components/ProductsHome.css, amazon-clone/client/src/Components/ProductsHome.js
I added the feature that the user can click on the image to send them to the products, instead of only doing the link. @emmanuel-a-g
=> Image link

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/NavBar.js
=> New feature: class to function component

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/ProductsList.js
Fixed an uppercase issue on the title
=> Uppercase title on products list

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/SignUp.js, amazon-clone/client/src/contexts/AuthContext.js, amazon-clone/client/src/index.js, amazon-clone/package-lock.json
@leal10 can you please review??
=> Adding to database cart

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/NavBar.css, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/ProductsResult.js, amazon-clone/client/src/Components/Searched.js, amazon-clone/client/src/utility/Search.js
@leal10 can you please review? Thank you!
=> Search box and results component

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Basket.js, amazon-clone/client/src/Components/ProductsList.js
@emmanuel-a-g Fixed the path issue with the account component and also I rounded the subtotal to two decimal places. Can you please review. Thanks
=> Fixed the path issue and the subtotal issue

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Account.css, amazon-clone/client/src/Components/Account.js, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/UserInfoChange.css, amazon-clone/client/src/Components/UserInfoChange.js
@emmanuel-a-g Hey bro whenever you have time can you please review this. Thanks
=> Change info

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/Account.js, amazon-clone/client/src/Components/BottomNavBar.css, amazon-clone/client/src/Components/BottomNavBar.js, amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/NavBar.css, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/PrivateAccount.js, amazon-clone/client/src/Components/PrivateUserInfo.js, amazon-clone/client/src/Components/SingleProduct.js, amazon-clone/client/src/utility/Search.js
@leal10 can you please review? If there's anything you're unsure lmk!
=> Bottom nav bar and private routes

amazon-clone/client/src/Components/BottomNavBar.css, amazon-clone/client/src/Components/BottomNavBar.js, amazon-clone/client/src/Components/SignUp.js, amazon-clone/client/src/Components/UserInfoChange.js
@leal10 can you please review? Thank you!
=> Updated a couple of details

amazon-clone/client/src/Components/UserInfoChange.js, amazon-clone/client/src/contexts/AuthContext.js, amazon-clone/client/src/firebase.js
@leal10 created the functions to update name, email, password, and delete user:) let me know if you need help on the modal logic, thanks bro!
=> created update name, password, email and delete user

amazon-clone/client/src/Components/NavBar.css, amazon-clone/client/src/Components/NavBar.js
Fixed the border issue in the NavBar
=> Account border

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/DeleteAccount.js, amazon-clone/client/src/Components/Login.css, amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/PrivateAccount.js, amazon-clone/client/src/Components/PrivateRoute.js, amazon-clone/client/src/Components/SignUp.js, amazon-clone/client/src/Components/UserInfoChange.css, amazon-clone/client/src/Components/UserInfoChange.js, amazon-clone/client/src/contexts/AuthContext.js
@leal10  please review, allows to delete the account and database document of the user :)
=> Delete User Account completed

amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/UserInfoChange.js
=> Last css changes

amazon-clone/client/src/Components/UserInfoChange.js
@emmanuel-a-g Fixed the buttons in Login and the modal.
=> Disabled button

amazon-clone/client/src/Components/DeleteAccount.js, amazon-clone/client/src/contexts/AuthContext.js
fixed my errors in delete user and update profile name, please review @leal10 ?
=> Fixed errors delete user

amazon-clone/client/src/App.js, amazon-clone/client/src/Components/BottomNavBar.css, amazon-clone/client/src/Components/BottomNavBar.js, amazon-clone/client/src/Components/Carousel.css, amazon-clone/client/src/Components/Carousel.js, amazon-clone/client/src/Components/ProductsHome.css, amazon-clone/client/src/Components/ProductsHome.js
@leal10 please review these changes? thank you!
=> Style update to account home and bottomNavBar

amazon-clone/client/package.json, amazon-clone/client/src/App.js
=> changes made for deployment

amazon-clone/client/src/Components/Basket.js, amazon-clone/client/src/Components/BottomCarousel.css, amazon-clone/client/src/index.css
@leal10 please review? Changes made for deployment
=> deployment changes css

amazon-clone/client/src/Components/Account.css, amazon-clone/client/src/Components/Account.js, amazon-clone/client/src/Components/BottomNavBar.css, amazon-clone/client/src/Components/BottomNavBar.js, amazon-clone/client/src/Components/ProductsHome.css, amazon-clone/client/src/Components/ProductsHome.js, amazon-clone/client/src/Components/ProductsList.css, amazon-clone/client/src/Components/ProductsList.js, amazon-clone/client/src/Components/SingleProduct.css, amazon-clone/client/src/Components/SingleProduct.js, amazon-clone/client/src/index.css
=> Added css grid on some components

amazon-clone/client/src/Components/Account.css, amazon-clone/client/src/Components/Account.js, amazon-clone/client/src/Components/ForgotPassword.js, amazon-clone/client/src/Components/Login.css, amazon-clone/client/src/Components/Login.js, amazon-clone/client/src/Components/ProductsHome.css, amazon-clone/client/src/Components/ProductsHome.js, amazon-clone/client/src/Components/SignUp.css, amazon-clone/client/src/Components/SignUp.js, amazon-clone/client/src/Components/SingleProduct.css, amazon-clone/client/src/Components/UserInfoChange.css, amazon-clone/client/src/Components/UserInfoChange.js, amazon-clone/client/src/index.css
@leal10 please review, thanks bro!
=> ready for new amazon-clone release

amazon-clone/client/src/Components/NavBar.css
fixed nav-bar search bar alignment and font-size
=> aligned search bar and added media query

amazon-clone/client/src/Components/Account.css, amazon-clone/client/src/Components/BottomCarousel.css, amazon-clone/client/src/Components/PrivateUserInfo.js, amazon-clone/client/src/Components/ProductsHome.css, amazon-clone/client/src/Components/ProductsList.css, amazon-clone/client/src/Components/UserInfoChange.css, amazon-clone/client/src/Components/UserInfoChange.js, amazon-clone/client/src/index.css
@leal10 please review? Thank you!
=> Amazon two

amazon-clone/client/src/Components/Basket.css, amazon-clone/client/src/Components/Basket.js
Fixed the css in the checkout component and its now responsive. @emmanuel-a-g
=> Checkout css

amazon-clone/client/src/Components/BottomNavBar.js
=> New branch minor changes

amazon-clone/client/public/index.html, amazon-clone/client/src/Components/Basket.css, amazon-clone/client/src/Components/BottomCarousel.css, amazon-clone/client/src/Components/NavBar.css, amazon-clone/client/src/Components/NavBar.js, amazon-clone/client/src/Components/ProductsList.js, amazon-clone/client/src/Components/ProductsResult.js, amazon-clone/client/src/Components/Searched.js, amazon-clone/client/src/Components/SingleProduct.js
Please review @leal10 !:)
Thanks bro!
=> commit one w nav bar and search, font size
